version: '3.8'
services:
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
    ports:
      - '8081:8080'

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

volumes:
  db:
    driver: local
