version: '3.8'
services:
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      TZ: Europe/Berlin
    ports:
      - '8081:8080'

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TZ=Europe/Berlin
    ports:
      - '5432:5432'
    volumes: 
      - todo-db:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD
      - TZ=Europe/Berlin
      - PGTZ=GMT+2
    ports:
      - '6379:6379'

volumes:
  todo-db:
    driver: local
