version: '3.8'
services:
  nginx:
    build:
      context: nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    networks:
      - web

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
    ports:
      - '8081:8080'
    networks:
      - internal

  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    networks:
      - web

  backend:
    build:
      context: backend
    environment:
      - AUTH_SECRET_KEY=${PROD_AUTH_SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${PROD_POSTGRES_PASSWORD}@db:5432/todo?schema=public
      - REDIS_CLIENT_URL=redis://:${PROD_REDIS_PASSWORD}@redis:6379
      - ADMIN_PASSWORD
      - USER_PASSWORD
    depends_on:
      - db
      - redis
    networks:
      - web
      - internal

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
    volumes: 
      - todo-prod-db:/var/lib/postgresql/data
    networks:
        - internal

  redis:
    image: 'bitnami/redis:6.2'
    environment:
      - REDIS_PASSWORD=${PROD_REDIS_PASSWORD}
    networks:
        - internal

volumes:
  todo-prod-db:
    driver: local

networks:
  web:
  internal:
