name: Build and push backend

on:
  push:
    paths:
      - backend/**
      - .github/workflows/**

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to ghcr
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: ghcr.io/chrishrb/todo-backend
          registry: ghcr.io
          directory: ./backend/
          dockerfile: ./backend/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
